"""Add voice agent request, voice agent, and call models

Revision ID: 423ec09828ad
Revises: 9489b6c9ff26
Create Date: 2025-12-02 00:38:10.086844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423ec09828ad'
down_revision: Union[str, None] = '9489b6c9ff26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_agent_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('real_estate_agent_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['real_estate_agent_id'], ['real_estate_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_voice_agent_request_agent_status', 'voice_agent_requests', ['real_estate_agent_id', 'status'], unique=False)
    op.create_index(op.f('ix_voice_agent_requests_real_estate_agent_id'), 'voice_agent_requests', ['real_estate_agent_id'], unique=False)
    op.create_index(op.f('ix_voice_agent_requests_status'), 'voice_agent_requests', ['status'], unique=False)
    op.create_table('voice_agents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('real_estate_agent_id', sa.String(), nullable=False),
    sa.Column('phone_number_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('use_default_prompt', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['real_estate_agent_id'], ['real_estate_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_agents_phone_number_id'), 'voice_agents', ['phone_number_id'], unique=False)
    op.create_index(op.f('ix_voice_agents_real_estate_agent_id'), 'voice_agents', ['real_estate_agent_id'], unique=True)
    op.create_index(op.f('ix_voice_agents_status'), 'voice_agents', ['status'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('voice_agent_id', sa.String(), nullable=False),
    sa.Column('real_estate_agent_id', sa.String(), nullable=False),
    sa.Column('twilio_call_sid', sa.String(), nullable=False),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('from_number', sa.String(), nullable=False),
    sa.Column('to_number', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('recording_sid', sa.String(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['real_estate_agent_id'], ['real_estate_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voice_agent_id'], ['voice_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calls_agent_created', 'calls', ['real_estate_agent_id', 'created_at'], unique=False)
    op.create_index('idx_calls_agent_status', 'calls', ['real_estate_agent_id', 'status'], unique=False)
    op.create_index('idx_calls_voice_agent_created', 'calls', ['voice_agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_calls_contact_id'), 'calls', ['contact_id'], unique=False)
    op.create_index(op.f('ix_calls_created_at'), 'calls', ['created_at'], unique=False)
    op.create_index(op.f('ix_calls_direction'), 'calls', ['direction'], unique=False)
    op.create_index(op.f('ix_calls_real_estate_agent_id'), 'calls', ['real_estate_agent_id'], unique=False)
    op.create_index(op.f('ix_calls_recording_sid'), 'calls', ['recording_sid'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_index(op.f('ix_calls_twilio_call_sid'), 'calls', ['twilio_call_sid'], unique=True)
    op.create_index(op.f('ix_calls_voice_agent_id'), 'calls', ['voice_agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calls_voice_agent_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_twilio_call_sid'), table_name='calls')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_recording_sid'), table_name='calls')
    op.drop_index(op.f('ix_calls_real_estate_agent_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_direction'), table_name='calls')
    op.drop_index(op.f('ix_calls_created_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_contact_id'), table_name='calls')
    op.drop_index('idx_calls_voice_agent_created', table_name='calls')
    op.drop_index('idx_calls_agent_status', table_name='calls')
    op.drop_index('idx_calls_agent_created', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_voice_agents_status'), table_name='voice_agents')
    op.drop_index(op.f('ix_voice_agents_real_estate_agent_id'), table_name='voice_agents')
    op.drop_index(op.f('ix_voice_agents_phone_number_id'), table_name='voice_agents')
    op.drop_table('voice_agents')
    op.drop_index(op.f('ix_voice_agent_requests_status'), table_name='voice_agent_requests')
    op.drop_index(op.f('ix_voice_agent_requests_real_estate_agent_id'), table_name='voice_agent_requests')
    op.drop_index('idx_voice_agent_request_agent_status', table_name='voice_agent_requests')
    op.drop_table('voice_agent_requests')
    # ### end Alembic commands ###

