"""Add contacts table and property contact_id foreign key

Revision ID: 9489b6c9ff26
Revises: 8f9c20ebaeab
Create Date: 2025-11-30 16:09:20.495031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9489b6c9ff26'
down_revision: Union[str, None] = '8f9c20ebaeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('real_estate_agent_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['real_estate_agent_id'], ['real_estate_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_phone', 'contacts', ['real_estate_agent_id', 'phone_number'], unique=False)
    op.create_index(op.f('ix_contacts_phone_number'), 'contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_contacts_real_estate_agent_id'), 'contacts', ['real_estate_agent_id'], unique=False)
    op.drop_index('idx_documents_agent_id', table_name='documents')
    op.drop_index('idx_phone_numbers_agent_id', table_name='phone_numbers')
    op.drop_index('idx_phone_numbers_is_active', table_name='phone_numbers')
    op.add_column('properties', sa.Column('contact_id', sa.String(), nullable=True))
    op.drop_index('idx_properties_agent_id', table_name='properties')
    op.create_index('idx_agent_available', 'properties', ['real_estate_agent_id', 'is_available'], unique=False)
    op.create_index('idx_agent_type', 'properties', ['real_estate_agent_id', 'property_type'], unique=False)
    op.create_index('idx_contact_properties', 'properties', ['contact_id', 'is_available'], unique=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_contact_id'), 'properties', ['contact_id'], unique=False)
    op.create_index(op.f('ix_properties_is_available'), 'properties', ['is_available'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_real_estate_agent_id'), 'properties', ['real_estate_agent_id'], unique=False)
    op.create_foreign_key(None, 'properties', 'contacts', ['contact_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_agents_company_name', table_name='real_estate_agents')
    op.drop_index('idx_agents_full_name', table_name='real_estate_agents')
    op.drop_index('idx_agents_is_active', table_name='real_estate_agents')
    op.drop_index('idx_agents_is_verified', table_name='real_estate_agents')
    op.drop_index('idx_agents_verified_active', table_name='real_estate_agents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_agents_verified_active', 'real_estate_agents', ['is_verified', 'is_active'], unique=False)
    op.create_index('idx_agents_is_verified', 'real_estate_agents', ['is_verified'], unique=False)
    op.create_index('idx_agents_is_active', 'real_estate_agents', ['is_active'], unique=False)
    op.create_index('idx_agents_full_name', 'real_estate_agents', ['full_name'], unique=False)
    op.create_index('idx_agents_company_name', 'real_estate_agents', ['company_name'], unique=False)
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_index(op.f('ix_properties_real_estate_agent_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_is_available'), table_name='properties')
    op.drop_index(op.f('ix_properties_contact_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.drop_index('idx_contact_properties', table_name='properties')
    op.drop_index('idx_agent_type', table_name='properties')
    op.drop_index('idx_agent_available', table_name='properties')
    op.create_index('idx_properties_agent_id', 'properties', ['real_estate_agent_id'], unique=False)
    op.drop_column('properties', 'contact_id')
    op.create_index('idx_phone_numbers_is_active', 'phone_numbers', ['is_active'], unique=False)
    op.create_index('idx_phone_numbers_agent_id', 'phone_numbers', ['real_estate_agent_id'], unique=False)
    op.create_index('idx_documents_agent_id', 'documents', ['real_estate_agent_id'], unique=False)
    op.drop_index(op.f('ix_contacts_real_estate_agent_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone_number'), table_name='contacts')
    op.drop_index('idx_agent_phone', table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###

